### ISSUE TITLE
오브젝트들을 더 효율적으로 생성시키는 방법

### ISSUE THREAD

**Issue by FreeStyleChoi** [FreeStyleChoi/DefenseKingdom#6]
T_SDLbasic 브랜치에서 오브젝트들의 개수를 제한을 두고 있어서 불편한데 오브젝트 구조체 변수를 동적 할당으로 선언 해준 뒤 화면에서 사라졌을 때는 free나, realloc을 사용하고 onScreen을 false 로 해주면 제한 없이 오브젝트를 만들 수 있습니다. 그 기능을 구현했으면 좋겠습니다.

**Comment by seungjec** [comment]
컴퓨터가 실제로 메모리를 잡고 풀 때마다 시간 소모가 발생합니다.
따라서 화면의 오브젝트가 생기고 사라질때마다 해당 오브젝트 변수를 생성/삭제하면 FPS가 낮아질 수 있습니다.
이것은 별도의 테스트 브랜치를 만들어서 확인해 봅시다.
